public with sharing class two_calculator {
    public static void add(){
        Integer a=10,b=20;
        Integer sum=a+b;
        System.debug('Addition of a and b is '+sum);
    }
        public static void sub(){
        Integer e=10,f=20;
        Integer sub=e+f;
        System.debug('Subtraction of a and b is '+sub);
    }
        public static void mul(){
        Integer g=10,h=20;
        Integer mul=g+h;
        System.debug('Multiplication of a and b is '+mul);
    }
        public static void div(){
        Integer i=10,j=20;
        Integer div=i+j;
        System.debug('Division of a and b is '+div);
     }
}